spring.application.name=siw-books

#==================================
# = Datasource
#==================================
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/book
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#==================================
# = Web server
#==================================
server.port=8080
#==================================
# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#==================================
# = Messages configuration
#==================================
spring.messages.basename=messages/messages
spring.messages.encoding=ISO-8859-1
#==================================
# = Logging OAuth2 configuration
#==================================

#Github logging
spring.security.oauth2.client.registration.github.client-id=Ov23liE29KgIqLuwxo3Y
spring.security.oauth2.client.registration.github.client-secret=a1bbd8230657262585d43f93f4c12287e7b6634c
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.provider.github.user-name-attribute=login

#Google logging
spring.security.oauth2.client.registration.google.client-id=1016293788092-iv363lbrcq94ea35r7etjnbpv4tkkj5u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

logging.level.org.springframework.security=TRACE